### ISSUE TITLE
patch功能错误

### ISSUE THREAD

**Issue by sung3r** [CTSinon/Autopwn#1]
patch LIBC文件夹里2.23 x86的libc，执行ldd level3报错，直接运行也报以下错误
Inconsistency detected by ld.so: dl-version.c: 205: _dl_check_map_versions: Assertion `needed != NULL' failed!

**Comment by sung3r** [comment]
patch ./ctf/attack.py

            needed = []
            for replace in self.needed:
                replace = replace.split('/')
                replace.insert(-1,':')
                replace = '/'.join(replace)
                needed.append(replace)
            print needed
            for replace in needed:
                command = "patchelf --set-rpath {} {}".format(replace, elf)
                log.info("Executing: " + command)
                exit_value += os.system(command)

**Comment by m4tsuri** [comment]
谢谢反馈，请问可否看一下引起错误的代码

**Comment by sung3r** [comment]
发现是patchelf自身问题。。。--replace-needed参数会出问题，改--set-rpath就可以
<img width="1198" alt="WeChat66fc3e6489ebbc87b3a688581fe95680" src="https://user-images.githubusercontent.com/61681732/83901583-93caf300-a78d-11ea-8a0c-5c82c5790260.png">

**Comment by m4tsuri** [comment]
我几天前好像也遇到过一个关于patchelf的问题。应该是我的代码的锅，最新版的代码应该已经解决了该问题。（不知道我们说的是不是同一个问题
