### ISSUE TITLE
尝试example文件夹中的例子 python ./exp.py patch 报错 无法找到包

### ISSUE THREAD

**Issue by fengshansi** [CTSinon/Autopwn#2]
运行python ./exp.py patch 报错如下
Traceback (most recent call last):
  File "./exp.py", line 39, in <module>
    ctf(argv, exp, get_flag,
TypeError: ctf() got multiple values for argument 'inter'

**Comment by m4tsuri** [comment]
你好，实例文件已更新

**Comment by fengshansi** [comment]
万分感谢
